
; inc: increments by one, dec: decrements by one.
; proc 1
(define (+ a b)
  (if (= a 0)
    b
    (inc (+ (dec a) b)))) 


; proc 2
(define (+ a b)
  (if (= a 0)
    b
    (+ (dec a) (inc b))))


(+ 4 5)
; proc 1
; (+ 4 5)
; (inc (+ (dec 4) 5))
; (inc (inc (+ (dec (dec 4)) 5)))
; (inc (inc (inc (+ (dec (dec (dec 4))) 5))))
; (inc (inc (inc (inc (dec (dec (dec (dec 4))) 5)))))
; [...]

; Or rather (no need to complicate things):

; proc 1
; (inc (+ 3 5))
; (inc (inc (+ 2 5)))
; (inc (inc (inc (+ 1 5))))
; (inc (inc (inc (inc (+ 0 5)))))
; (inc (inc (inc (inc  5))))
; (inc (inc (inc 6))))
; (inc (inc 7))
; (inc 8)
; 9

; proc 2
; (+ 3 6)
; (+ 2 7)
; (+ 1 8)
; (+ 0 9)
; 9

; process generated by proc 1 is recursive, process generated by proc 2 is iterative.
